CREATE TABLE IF NOT EXISTS listings_current (
    id SERIAL PRIMARY KEY,
    source TEXT NOT NULL,
    source_listing_id TEXT NOT NULL,
    address TEXT,
    city TEXT,
    state TEXT,
    zip TEXT,
    list_price NUMERIC,
    beds NUMERIC,
    baths NUMERIC,
    sqft NUMERIC,
    property_type TEXT,
    status TEXT,
    days_on_market INTEGER,
    first_seen_date DATE,
    last_seen_date DATE,
    price_per_sqft NUMERIC,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (source, source_listing_id)
);